// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./../src/components/footer/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    Leftside1: typeof import('./../src/components/side/leftside1.vue')['default']
    Leftside2: typeof import('./../src/components/side/leftside2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    State: typeof import('./../src/components/state.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
}
